[package]
name = "vgpu-quantum-transcendence-v2"
version = "2.0.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
num-complex = { workspace = true }
num_cpus = { workspace = true }