[package]
name = "vgpu-rendering-infinity"
version = "1.5.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
nalgebra = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }